remote_theme: pages-themes/tactile@v0.2.0
plugins:
- jekyll-remote-theme

title: Windows MIDI Services Documentation
description: User and developer documentation for the Windows MIDI Services project
#show_downloads: true
