#site settings

title: Windows MIDI Services Documentation
description: User and developer documentation for the Windows MIDI Services project
#show_downloads: true
twitter_username: pete_brown
github_username: psychlist1972

#theme
remote_theme: pages-themes/slate@v0.2.0

#plugins

plugins:
- jekyll-remote-theme

